spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        format_sql: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/atopybook
    username: sa
    password:
    driver-class-name: org.h2.Driver