spring:
  h2:
    console:
      enabled: true
      path: /test_db

  datasource:
    driver-class-name: org.h2.Driver #h2 driver configuration
    url: jdbc:h2:tcp://localhost/~/atopibook
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug